os: linux
dist: xenial
language: node_js
node_js:
- "14"

install:
- npm install

jobs:
  include:
    - stage: qualify
      script: npm run lint
    - script: npm run test && bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - "node_modules"