os: linux
dist: xenial
language: node_js
node_js:
- "14"

install:
- npm install

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
    - script: npm run test
    - script: npm run test
    - stage: coverage
      script: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - "node_modules"