os: linux
dist: xenial
language: node_js
node_js:
- "14"

install:
- npm install

jobs:
  include:
    - stage: qualify
      script:
      - npm run lint
      - npm run test browser.type=chromium
      - sudo apt-get install -y libdbus-glib-1-2 libxt6
      - npm run test browser.type=firefox
      - npm run test browser.type=webkit
      - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - "node_modules"