language: node_js
node_js:
- "14"

install:
- npm install

jobs:
  include:
    - stage: lint & test
      script: npm run lint
      script: npm run test
    - stage: report
      script: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - "node_modules"