interactive-browser: Custom Browser (interactive) {
  Session
  Test
  UI
}

cli-process: JustTest CLI

just-test-process: Main process {
  server: Server

  client-nodejs: Tests runner - NodeJS {
    Session
    Test
  }

  client-browser: Tests runner - Browser (managed) {
    Session
    Test
  }

  client-nodejs.session <-> server
  client-nodejs.test <-> server
  client-browser.session <-> server
  client-browser.test <-> server
}

just-test-process.server <-> interactive-browser.session
just-test-process.server <-> interactive-browser.test
just-test-process.server <-> interactive-browser.ui
just-test-process.server <-> cli-process
