name: Build

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS (14)
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Try cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true