name: Publish

on:
  pull_request:
    branches:
      - 'master'

jobs:
  publish:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)

      - name: Publish/Deploy
        run: npm publish