name: Publish

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [closed]
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS (for build/test)
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)

      - name: Publish/Deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
        run: npm publish --access public
