name: Publish

on:
  pull_request:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Try cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /home/runner/.cache/ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)

      - name: Publish/Deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
        run: npm publish --access public
